"""empty message

Revision ID: 4f198055a101
Revises: 34c098fe7e7f
Create Date: 2023-08-16 21:42:01.440462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f198055a101'
down_revision = '34c098fe7e7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(), nullable=False, server_default='thumbnail.jpeg'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    # ### end Alembic commands ###
